### ISSUE TITLE
Provide person-weeks exposure in an age-stratified way?

### ISSUE THREAD

**Issue by tomwenseleers** [jschoeley/mocy#1]
Thanks for the nice work!
Right now provided variable personweeks is the total population size across all age classes, interpolated between the January 1 censuses.
I was wondering if, instead, it would not be possible to provide interpolated population size figures specifically for the given age strata & sexes?
After all, if one fits mortality rates with a log link Poisson or negative binomial GLM, one would typically like to include a log(personweeks) exposure offset term defined in terms of person weeks in each specific sex & age class category, right?

Maybe this could be calculated from some of the files provided here,
https://www.mortality.org/Data/ZippedDataFiles ?

**Comment by jschoeley** [comment]
Thank you. No, personweeks is stratified by age and sex. I just looked through the latest mocy release and it looks alright. Here's an example for Austria:
 
![image](https://user-images.githubusercontent.com/10901917/202189648-352b6a7b-bde5-4826-bc97-e764bb77115a.png)

**Comment by tomwenseleers** [comment]
Ha sorry - I see now, never mind, thanks (I should have looked more carefully)!
Also saw you just did a push to also include temperature data for 2022, but I think the file at https://osf.io/download/ydpvu/ has not yet been updated with that - would it be possible by any chance to push an updated datafile, with the temperature data of 2022 included? Thanks for the nice work!

**Comment by jschoeley** [comment]
Will do.
